FROM node:22-alpine

WORKDIR /app

# Sao chép package.json
COPY package.json ./

# Cài đặt dependencies bên trong container
RUN npm install

# Sao chép toàn bộ mã nguồn
COPY . .

# Expose cổng của Vite
EXPOSE 5173

# Chạy frontend với flag --host 0.0.0.0 để thiết bị di động trong cùng Wi-Fi có thể truy cập được
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
